### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by li-ziang** [li-ziang/THU-Java-2021#1]
This is a design doc for our Java homework, totally depending on the [Document](https://roim1998.github.io/Tsinghua-Java/) provided by Bowen Zhao.
If you encounter any problems, please check the [Java Android Documentation](https://developer.android.com/guide?hl=zh-cn) first. 

repo 参考 https://github.com/Guangxuan-Xiao/COVID-19-News-App ， https://github.com/icycookies/newsapp

app应该最低支持 [java8](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html)
## 基础功能
- [x] #2
    - [x] #6
    - [x] #7
- [ ] **本地缓存**：实现实体详情页的本地储存（课程会提供静态文件调试，后期可能改成调用api），使能够离线浏览详情页，访问过的变成黑色标记。
- [ ] #8
- [ ] **实体详情**：
  - [ ] #16
  - [x] #17
- [x] **知识问答**：问答机器人页面（使用[API](http://open.edukg.cn/help)）。
- [ ] **分享收藏**： 实现[微信SDK](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Share_and_Favorites/Android.html)分享，生成分享页面，需要带有摘要，内容需要带有摘要。
- [x] **用户登陆**：实现登陆功能，收藏信息同步到服务器，保存浏览记录 。

## 附加功能
- [x] **专项测试**：出题，打分。
- [ ] **知识梳理**：给出一个复习提纲
- [ ] **试题推荐**：根据历史记录进行试题推荐（好做，分多），推荐算法参考 https://github.com/hexiangnan/neural_collaborative_filtering

## 基础页面参考
![fig 1.png](https://i.loli.net/2021/08/10/ZuSxfLbD2zGCYkT.png)
![fig 2.png](https://i.loli.net/2021/08/10/f9xZckpYu6V5mDv.png)
